import Link from 'next/link';
import { answerSupport, extractInvoice, inquirySamples, invoiceSamples, parseInquiry, validateInvoice } from '@/lib/demos';
import { demoServices, services } from '@/lib/site';
export default function DemoContext({ slug }: { slug: string }) {
  const inquiry = parseInquiry(inquirySamples.complete);
  const support = answerSupport('How long does delivery take?');
  const invoice = extractInvoice(invoiceSamples.valid);
  const previews: Record<string, { task: string; output: string; build: string }> = {
    'inquiry-assistant': { task: 'A service inquiry arrives as free text. Someone must identify the contact, copy requirements into a lead record and prepare a first reply.', output: `Contact: ${inquiry.contact.name} · ${inquiry.contact.company}\nTools: ${inquiry.requirements.tools}\nRequest: ${inquiry.requirements.request}\nValidation: ${inquiry.missing.length ? 'Missing fields' : 'Required fields present'}\nNext: create local lead DEMO-001, then review the response draft.`, build: 'Scope an intake connection, agreed lead destination, missing-information handling and a reply approval queue. The local preview does not connect to a CRM or send email.' },
    'support-assistant': { task: 'A support team repeatedly checks policies before replying. Questions outside those policies need a clear handoff.', output: `Question: How long does delivery take?\nAnswer: ${support.answer}\nSource: ${support.sources[0].id} · ${support.sources[0].title}\nOutside coverage: human handoff, with no unsupported answer.`, build: 'Scope approved knowledge sources, retrieval, source citations, evaluation questions and human handoff. Live language-model retrieval and help-desk connections require implementation; this preview uses conservative phrase matching.' },
    'document-processing': { task: 'Invoice fields are copied into a sheet. Missing details and incorrect totals must be caught before the data moves on.', output: `Invoice: ${invoice.invoice}\nSupplier: ${invoice.supplier}\nSubtotal: ${invoice.currency} ${invoice.subtotal}\nTax: ${invoice.currency} ${invoice.tax}\nTotal: ${invoice.currency} ${invoice.total}\nValidation: ${validateInvoice(invoice).length ? 'Review errors' : 'Field and arithmetic checks passed'}\nExport: CSV or JSON after human review.`, build: 'Scope the document format, extracted fields, validation rules, review queue and export destination. This text-only preview includes no PDF upload, OCR, accounting sync or authenticity check.' },
  };
  const preview = previews[slug];
  if (!preview) return null;
  return <section className="demo-context" aria-labelledby="sample-output-heading"><div><p className="eyebrow">THE ORIGINAL TASK</p><p>{preview.task}</p><h2>What BuildZn can implement</h2><p>{preview.build}</p><div className="demo-service-links">{(demoServices[slug] || []).map(service => <Link key={service} className="text-link" href={`/services/${service}`}>{services.find(s => s.slug === service)?.name} ↗</Link>)}</div></div><div><p className="eyebrow">ACTUAL SAMPLE OUTPUT / FICTIONAL DATA</p><h2 id="sample-output-heading">See the result before trying it.</h2><pre className="sample-record">{preview.output}</pre><p className="field-help">Generated from the same sample inputs and deterministic functions used below. This is a BuildZn demonstration, not a customer result. Try the steps to inspect the fields, review gates and exceptions.</p></div></section>;
}
