'use client';
import { useState } from 'react';
import { answerSupport, extractInvoice, inquirySamples, invoiceCsv, invoiceSamples, knowledge, parseInquiry, validateInvoice, type Invoice } from '@/lib/demos';

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="demo-panel"><h3>{title}</h3>{children}</div>; }
export default function DemoWorkbench({ slug }: { slug: string }) {
  return <section className="demo-workbench" aria-label="Interactive sample demonstration"><div className="demo-topbar"><span className="status-dot"/><strong>BuildZn demonstration</strong><span>Sample data · Local preview</span></div><p className="demo-disclosure">Working browser steps with recorded response templates. No live AI model, paid account or external connection. Use sample data only; inputs stay in this page and are cleared on reload.</p>{slug === 'inquiry-assistant' ? <Inquiry/> : slug === 'support-assistant' ? <Support/> : <Document/>}</section>;
}
function Inquiry() {
  const [input, setInput] = useState(inquirySamples.complete);
  const [result, setResult] = useState<ReturnType<typeof parseInquiry> | null>(null);
  const [lead, setLead] = useState(false);
  const [approved, setApproved] = useState(false);
  const [draft, setDraft] = useState('');
  function reset(text: string) { setInput(text); setResult(null); setLead(false); setApproved(false); setDraft(''); }
  function parse() { setResult(parseInquiry(input)); setLead(false); setApproved(false); setDraft(''); }
  function createLead() { setLead(true); setDraft(`Hi ${result?.contact.name || 'there'},\n\nThanks for sharing your request${result?.contact.company ? ` from ${result.contact.company}` : ''}. We can review the workflow and tools before proposing a scope. Please share a sample input, the desired outcome and which actions need approval.\n\nThis is a recorded sample response template, pending human review. No price or delivery commitment has been made.\n\nUmair / BuildZn`); }
  return <div className="demo-columns"><Panel title="01 / Sample inquiry"><div className="demo-choices"><button className="chip" onClick={() => reset(inquirySamples.complete)}>Complete inquiry</button><button className="chip" onClick={() => reset(inquirySamples.incomplete)}>Missing information</button></div><label htmlFor="inquiry-input">Inquiry text</label><textarea id="inquiry-input" rows={9} maxLength={3000} value={input} onChange={e => reset(e.target.value)}/><p className="field-help">Keep the labeled format: Name, Email, Company, Tools, Request, Volume. This parser is intentionally limited.</p><button className="button button-small" onClick={parse} disabled={!input.trim()}>Structure requirements →</button></Panel><Panel title="02 / Requirements & lead"><div aria-live="polite">{result ? <><dl className="record">{Object.entries({ ...result.contact, ...result.requirements }).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{v || 'Not provided'}</dd></div>)}</dl>{result.missing.length ? <p className="validation-error">Needs clarification: {result.missing.join(', ')}. Lead creation is blocked.</p> : <><p className="validation-ok">Required fields present. Ready for a sample lead.</p><button className="button button-small button-secondary" disabled={lead} onClick={createLead}>{lead ? 'Sample lead created' : 'Create sample lead'}</button></>}{lead && <p className="sample-record">Lead DEMO-001 · New inquiry · Local memory only</p>}</> : <p>Structure the inquiry to inspect the fields and missing requirements.</p>}</div></Panel><Panel title="03 / Response for approval">{lead ? <><label htmlFor="response-draft">Recorded draft · editable</label><textarea id="response-draft" rows={10} value={draft} maxLength={3000} onChange={e => { setDraft(e.target.value); setApproved(false); }}/><button className="button button-small" disabled={approved || !draft.trim()} onClick={() => setApproved(true)}>Approve draft locally</button><p role="status" className={approved ? 'validation-ok' : 'field-help'}>{approved ? 'Approved in this preview. Nothing has been sent.' : 'Human approval required. No email or CRM connection.'}</p></> : <p>Create a valid sample lead to prepare a response draft.</p>}</Panel></div>;
}
function Support() {
  const [question, setQuestion] = useState('How long does delivery take?');
  const [result, setResult] = useState<ReturnType<typeof answerSupport> | null>(null);
  function change(q: string) { setQuestion(q); setResult(null); }
  return <div className="demo-columns"><Panel title="01 / Sample knowledge base">{knowledge.map(source => <article className="kb-source" key={source.id} id={source.id}><h4>{source.id} / {source.title}</h4><p>{source.text}</p></article>)}</Panel><Panel title="02 / Ask a question"><div className="demo-choices"><button className="chip" onClick={() => change('How long does delivery take?')}>Delivery</button><button className="chip" onClick={() => change('Can I return an unused item?')}>Returns</button><button className="chip" onClick={() => change('Can I return a used item after 30 days?')}>Outside coverage</button></div><label htmlFor="support-question">Sample customer question</label><textarea id="support-question" rows={5} value={question} maxLength={1000} onChange={e => change(e.target.value)}/><button className="button button-small" disabled={!question.trim()} onClick={() => setResult(answerSupport(question))}>Find grounded answer →</button><p className="field-help">Exact, conservative phrase matching chooses recorded answers. Unrecognized wording hands off to a person.</p></Panel><Panel title="03 / Answer or handoff"><div aria-live="polite">{result ? <><p className={result.status === 'grounded' ? 'validation-ok' : 'validation-error'}>{result.status === 'grounded' ? 'Covered by sample sources' : 'Human handoff required'}</p><p>{result.answer}</p>{result.sources.map(source => <a className="source-link" key={source.id} href={`#${source.id}`}>Source: {source.id} — {source.title}</a>)}{result.handoff && <pre className="sample-record">{result.handoff}</pre>}<p className="field-help">No reply sent. No support ticket opened.</p></> : <p>Ask a question to inspect the answer, sources or handoff.</p>}</div></Panel></div>;
}
function Document() {
  const [input, setInput] = useState(invoiceSamples.valid);
  const [fields, setFields] = useState<Invoice | null>(null);
  const [reviewed, setReviewed] = useState(false);
  const [exported, setExported] = useState('');
  const errors = fields ? validateInvoice(fields) : [];
  function change(text: string) { setInput(text); setFields(null); setReviewed(false); setExported(''); }
  function update(key: keyof Invoice, value: string) { if (fields) setFields({ ...fields, [key]: value }); setReviewed(false); setExported(''); }
  function download(format: 'csv' | 'json') {
    if (!fields || !reviewed || validateInvoice(fields).length) return;
    const data = format === 'csv' ? invoiceCsv(fields) : JSON.stringify({ ...fields, demonstration: true, reviewed: true }, null, 2);
    const url = URL.createObjectURL(new Blob([data], { type: format === 'csv' ? 'text/csv;charset=utf-8' : 'application/json' }));
    const link = document.createElement('a'); link.href = url; link.download = `buildzn-sample-invoice.${format}`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setExported(`Sample ${format.toUpperCase()} export prepared. No accounting records changed.`);
  }
  return <div className="demo-columns"><Panel title="01 / Sample invoice"><div className="demo-choices"><button className="chip" onClick={() => change(invoiceSamples.valid)}>Valid invoice</button><button className="chip" onClick={() => change(invoiceSamples.mismatch)}>Mismatched total</button></div><label htmlFor="invoice-input">Invoice text</label><textarea id="invoice-input" rows={9} value={input} maxLength={3000} onChange={e => change(e.target.value)}/><button className="button button-small" disabled={!input.trim()} onClick={() => { setFields(extractInvoice(input)); setReviewed(false); setExported(''); }}>Extract fields →</button><p className="field-help">Text extraction in the shown format. No PDF upload, OCR or model call.</p></Panel><Panel title="02 / Validate & correct">{fields ? <><div className="invoice-fields">{(Object.keys(fields) as (keyof Invoice)[]).map(key => <div key={key}><label htmlFor={`invoice-${key}`}>{key}</label><input id={`invoice-${key}`} value={fields[key]} maxLength={160} onChange={e => update(key, e.target.value)}/></div>)}</div><div aria-live="polite">{errors.length ? <ul className="validation-error">{errors.map(error => <li key={error}>{error}</li>)}</ul> : <p className="validation-ok">Required fields, date, currency and arithmetic checks passed.</p>}</div></> : <p>Extract the invoice to inspect and correct its fields.</p>}</Panel><Panel title="03 / Review & export"><p>Compare extracted values with the source invoice before approving. Validation does not establish authenticity or accounting correctness.</p><label className="review-checkbox"><input type="checkbox" disabled={!fields || errors.length > 0} checked={reviewed} onChange={e => { setReviewed(e.target.checked); setExported(''); }}/><span>I reviewed the sample fields against the invoice.</span></label><div className="demo-choices"><button className="button button-small" disabled={!reviewed || errors.length > 0} onClick={() => download('csv')}>Export CSV</button><button className="button button-small button-secondary" disabled={!reviewed || errors.length > 0} onClick={() => download('json')}>Export JSON</button></div><p role="status" className="field-help">{exported || 'Export stays blocked until validation passes and review is confirmed. Changing a field clears approval.'}</p></Panel></div>;
}
