import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {initialState}=require('../.test-build/lib/ops/core.js');
const {captureWithNotification,claimNotification,finishNotification,deliverNotification,notificationPayload}=require('../.test-build/lib/ops/inquiry-mail.js');
const sample={name:'Controlled inquiry',email:'sample@example.com',message:'Controlled inquiry for mail pipeline verification only.'};
function setup(){const state=initialState();const {leadId}=captureWithNotification(state,sample,true);return {state,leadId,transact:async fn=>fn(state)};}
test('storage capture queues one owner alert and identical inquiry retries retain the same record',()=>{const {state,leadId}=setup();assert.equal(captureWithNotification(state,sample,true).leadId,leadId);assert.equal(Object.keys(state.inquiryNotifications).length,1);assert.equal(state.leads.length,1);assert.equal(state.inquiryNotifications[leadId].attempts,0);const disabled=initialState();const r=captureWithNotification(disabled,sample,false);assert.equal(disabled.inquiryNotifications[r.leadId].status,'disabled');});
test('concurrent attempts and repeated submissions send only once after provider acceptance',async()=>{const {state,leadId,transact}=setup();let calls=0;const send=async()=>{calls++;await new Promise(r=>setTimeout(r,5));return Response.json({ok:true});};await Promise.all([deliverNotification(leadId,{transact,send,enabled:true}),deliverNotification(leadId,{transact,send,enabled:true})]);assert.equal(await deliverNotification(leadId,{transact,send,enabled:true}),'accepted');assert.equal(calls,1);assert.equal(state.inquiryNotifications[leadId].status,'accepted');assert.equal(state.leads.length,1);});
test('known rejection keeps the lead and supports only three bounded inspected attempts',async()=>{const {state,leadId,transact}=setup();let calls=0;const send=async()=>{calls++;return Response.json({error:'quota'}, {status:429});};for(let i=0;i<5;i++)assert.equal(await deliverNotification(leadId,{transact,send,enabled:true}),'failed');assert.equal(calls,3);assert.equal(state.leads.length,1);assert.equal(state.inquiryNotifications[leadId].attempts,3);});
test('timeouts, 5xx and invalid success bodies are uncertain and cannot be resent',async()=>{for(const send of [async()=>{throw new Error('secret provider failure');},async()=>new Response('unavailable',{status:503}),async()=>new Response('not-json'),async()=>Response.json({ok:false})]){const {state,leadId,transact}=setup();let calls=0;const counted=async(...args)=>{calls++;return send(...args);};assert.equal(await deliverNotification(leadId,{transact,send:counted,enabled:true}),'uncertain');assert.equal(await deliverNotification(leadId,{transact,send:counted,enabled:true}),'uncertain');assert.equal(calls,1);assert(!state.inquiryNotifications[leadId].error.includes('secret'));assert.equal(state.leads.length,1);}});
test('lost delivery-status write preserves the sending claim and never repeats the external send',async()=>{const {state,leadId}=setup();let writes=0,calls=0;await assert.rejects(()=>deliverNotification(leadId,{enabled:true,transact:async fn=>{if(++writes===2)throw new Error('storage outage');return fn(state);},send:async()=>{calls++;return Response.json({ok:true});}}));assert.equal(state.inquiryNotifications[leadId].status,'sending');await deliverNotification(leadId,{enabled:true,transact:async fn=>fn(state),send:async()=>{calls++;return Response.json({ok:true});}});assert.equal(calls,1);assert.equal(state.leads.length,1);});
test('stale claims require reconciliation and stale completion tokens cannot override state',()=>{const {state,leadId}=setup();const now=Date.now(),attempt=claimNotification(state,leadId,now);assert.equal(claimNotification(state,leadId,now+120001).status,'uncertain');finishNotification(state,leadId,attempt.claim,'accepted');assert.equal(state.inquiryNotifications[leadId].status,'uncertain');});
test('the external alert contains only a reference and never the visitor brief or address',async()=>{const {state,leadId,transact}=setup();let payload;const send=async(_url,options)=>{payload=JSON.parse(options.body);return Response.json({ok:true});};await deliverNotification(leadId,{enabled:true,transact,send});assert.deepEqual(payload,notificationPayload(leadId));assert(!JSON.stringify(payload).includes(sample.email));assert(!JSON.stringify(payload).includes(sample.message));assert(payload.message.includes('/ops'));assert.equal(state.leads[0].drafts.length,0);});
