'use client';
import { useRef, useState } from 'react';
import type { Draft, Lead, State } from '@/lib/ops/core';
import projects from '@/content/business/projects.json';
import './workspace.css';
type View = 'pipeline' | 'content' | 'research' | 'reporting' | 'activity' | 'settings';
type Topic = {
    id: string;
    title: string;
    score: number;
    action: string;
    demand: string;
    reasons: string[];
    existing?: {
        route: string;
    };
};
function json(value: unknown) { return JSON.stringify(value, null, 2); }
function field(form: FormData, name: string) { return String(form.get(name) || ''); }
function Label({ name, children }: {
    name: string;
    children: React.ReactNode;
}) { return <label className="ops-field">{name}{children}</label>; }
export default function Workspace({ initial, signedIn, storage, initialError }: {
    initial: State | null;
    signedIn: boolean;
    storage: string;
    initialError: string;
}) {
    const [state, setState] = useState(initial), [logged, setLogged] = useState(signedIn), [view, setView] = useState<View>('pipeline'), [selected, setSelected] = useState(initial?.leads[0]?.id || ''), [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [busy, setBusy] = useState(false), [notice, setNotice] = useState(initialError), [isError, setIsError] = useState(!!initialError), [add, setAdd] = useState(false), [includeSamples, setIncludeSamples] = useState(false);
    const [now, setNow] = useState(() => Date.now());
    const failed = useRef<{
        signature: string;
        key: string;
    } | null>(null);
    async function refresh() { const r = await fetch('/api/ops/action'); const body = await r.json(); if (!r.ok)
        throw new Error(body.error); setState(body); setNow(Date.now()); return body as State; }
    async function act(action: string, data: Record<string, unknown> = {}) { setBusy(true); setNotice(''); setIsError(false); const signature = json({ action, data }), key = failed.current?.signature === signature ? failed.current.key : crypto.randomUUID(); failed.current = { signature, key }; try {
        const r = await fetch('/api/ops/action', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: json({ action, data, key }) });
        const result = await r.json();
        if (!r.ok)
            throw new Error(result.error);
        failed.current = null;
        await refresh();
        setNotice('Saved. Nothing has been sent or published.');
        if (result.result?.leadId)
            setSelected(result.result.leadId);
        return true;
    }
    catch (e) {
        setNotice(e instanceof Error ? e.message : 'Operation failed. Retry.');
        setIsError(true);
        return false;
    }
    finally {
        setBusy(false);
    } }
    if (!logged)
        return <div className="ops-login"><p className="eyebrow">BUILDZN / PRIVATE OPERATIONS</p><h1>Work that moves<br />the business forward.</h1><p>Lead records, evidence and drafts stay behind this sign-in. Every external action needs your review.</p><form onSubmit={async (e) => { e.preventDefault(); setBusy(true); try {
            const password = field(new FormData(e.currentTarget), 'password');
            const r = await fetch('/api/ops/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: json({ password }) });
            const d = await r.json();
            if (!r.ok)
                throw new Error(d.error);
            setLogged(true);
            await refresh();
        }
        catch (e) {
            setNotice((e as Error).message);
            setIsError(true);
        }
        finally {
            setBusy(false);
        } }}><Label name="Operations password"><input type="password" name="password" required autoComplete="current-password"/></Label><button className="ops-primary" disabled={busy}>{busy ? 'Signing in…' : 'Sign in securely'}</button></form>{notice && <p role="alert">{notice}</p>}<p className="ops-muted">Owner access · Sessions expire after eight hours.</p></div>;
    const lead = state?.leads.find(l => l.id === selected);
    const overdue = state?.leads.filter(l => l.dueAt && Date.parse(l.dueAt) <= now && !l.optedOut && !l.declined).length || 0;
    const approvalCount = (state?.leads.flatMap(l => l.drafts) || []).concat(state?.content || []).filter(d => d.approvedVersion !== d.version).length;
    const jobs = state?.jobs || [];
    const plan = jobs.filter(j => j.kind === 'seo-plan' && j.status === 'review').at(-1)?.result as {
        topics: Topic[];
        metricsDisclosure: string;
        searchConsoleContext: string;
    } | undefined;
    const visible = state?.leads.filter(l => (filter === 'all' || l.stage === filter) && `${l.name} ${l.email} ${l.company} ${l.source}`.toLowerCase().includes(search.toLowerCase())) || [];
    return <div className="ops-shell"><aside className="ops-sidebar"><a href="/ops" className="ops-brand">BuildZn<span>Operations</span></a><nav aria-label="Operations">{(['pipeline', 'research', 'content', 'reporting', 'activity', 'settings'] as View[]).map(item => <button key={item} aria-current={view === item ? 'page' : undefined} onClick={() => setView(item)}>{({ pipeline: 'Pipeline', research: 'Research & SEO', content: 'Content studio', reporting: 'Performance', activity: 'Activity & failures', settings: 'Operating controls' })[item]}</button>)}</nav><div className="ops-sidebar-bottom"><span className="ops-status">Human approval required</span><p>Sending and publishing are unavailable in this workspace.</p><button onClick={async () => { await fetch('/api/ops/session', { method: 'DELETE' }); location.reload(); }}>Sign out</button></div></aside><div className="ops-main"><header className="ops-header"><div><p className="ops-kicker">BUILDZN / SALES OPERATIONS</p><h1>{({ pipeline: 'Your next conversation.', research: 'Start with evidence.', content: 'Make the work useful.', reporting: 'What actually happened.', activity: 'A traceable operation.', settings: 'Bounded by design.' })[view]}</h1></div><button disabled={busy} onClick={() => refresh().catch(e => { setNotice(e.message); setIsError(true); })}>Refresh records</button></header><div className="ops-summary"><div><strong>{state?.leads.filter(l => !l.sample && l.stage !== 'lost').length || 0}</strong><span>Active non-sample records</span></div><div><strong>{approvalCount}</strong><span>Drafts awaiting review</span></div><div><strong>{overdue}</strong><span>Follow-ups due</span></div><div><strong>{jobs.filter(j => j.status === 'failed').length}</strong><span>Failures to inspect</span></div></div>{notice && <p className={'ops-notice ' + (isError ? 'ops-error' : '')} role={isError ? 'alert' : 'status'}>{notice}</p>}
 {view === 'pipeline' && <><div className="ops-toolbar"><Label name="Search leads"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Name, company or source"/></Label><Label name="Pipeline stage"><select value={filter} onChange={e => setFilter(e.target.value)}>{['all', 'inquiry', 'discovery', 'proposal', 'won', 'lost', 'handoff'].map(s => <option key={s}>{s}</option>)}</select></Label><button className="ops-primary" onClick={() => setAdd(!add)}>Add inquiry</button></div>{add && <section className="ops-panel"><h2>Capture an inquiry</h2><form onSubmit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await act('capture', Object.fromEntries([...f.entries()].map(([k, v]) => [k, k === 'sample' ? v === 'on' : v]))))
        setAdd(false); }} className="ops-grid-form"><Label name="Contact name"><input name="name" required maxLength={120}/></Label><Label name="Contact email"><input type="email" name="email" required maxLength={254}/></Label><Label name="Company"><input name="company" maxLength={160}/></Label><Label name="Acquisition source"><select name="source">{['direct', 'referral', 'search', 'social', 'public-request', 'controlled-test'].map(s => <option key={s}>{s}</option>)}</select></Label><Label name="Source detail"><input name="sourceDetail" placeholder="Original page, campaign or referral"/></Label><Label name="Tools"><input name="tools" maxLength={600}/></Label><Label name="Frequency / volume"><input name="volume"/></Label><Label name="Budget"><input name="budget"/></Label><Label name="Timing"><input name="timeline"/></Label><Label name="Inquiry brief"><textarea name="message" minLength={10} maxLength={5000} required rows={4}/></Label><label className="ops-check"><input type="checkbox" name="sample" defaultChecked/> Fictional sample / controlled test</label><button disabled={busy} className="ops-primary">Save inquiry</button></form></section>}<div className="ops-workbench"><section className="ops-lead-list" aria-label="Lead list">{visible.length === 0 ? <p className="ops-empty">No matching records. Add a controlled inquiry or discover public requests.</p> : visible.map(l => <button key={l.id} aria-pressed={selected === l.id} className="ops-lead-row" onClick={() => setSelected(l.id)}><span className="ops-row-top"><strong>{l.name}</strong><span className="ops-tag">{l.stage}</span></span><span>{l.company || l.email || 'Contact details not supplied'}</span><span className="ops-row-bottom">{l.source}{l.sample ? ' · Sample' : ''} · {l.missing.length} gaps</span></button>)}</section>{lead ? <LeadDetail key={lead.id} lead={lead} busy={busy} act={act} now={now}/> : <section className="ops-panel"><h2>Every lead has a next step.</h2><p>Select a record to review requirements, inspect evidence and prepare drafts. Sample records are labeled and excluded from performance by default.</p></section>}</div></>}
 {view === 'research' && <div className="ops-sections"><section className="ops-panel"><p className="ops-kicker">PUBLIC OPPORTUNITIES</p><h2>Requests, with context.</h2><p>Scan up to 30 recent official n8n support issues; retain up to eight explicit requests for relevant help. A support issue does not establish purchase intent or permission to contact.</p><button disabled={busy} className="ops-primary" onClick={() => act('discover')}>Discover public requests</button><p className="ops-muted">Read-only API research. No contact lists or outreach.</p></section><section className="ops-panel"><p className="ops-kicker">EXISTING BLOG WRITER</p><h2>Prioritize useful content.</h2><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('seo-plan', { csv: field(f, 'csv'), range: field(f, 'range') }); }}><Label name="Search Console Queries CSV (optional)"><textarea name="csv" rows={4} placeholder="Top queries,Clicks,Impressions,CTR,Position"/></Label><Label name="Reporting date range and filters"><input name="range" placeholder="For example: last 28 days, web, all countries"/></Label><button disabled={busy}>Build editorial plan</button></form>{plan && <><p className="ops-muted">{plan.searchConsoleContext}</p><p>{plan.metricsDisclosure}</p><div className="ops-topic-list">{plan.topics.map(t => <article key={t.id}><div><span className="ops-tag">{t.action}</span><span className="ops-muted">Priority {t.score} · heuristic, not search volume</span></div><h3>{t.title}</h3><p>{t.demand} · {t.reasons.join(' · ')}</p>{t.existing && <a href={t.existing.route}>{t.existing.route}</a>}<button disabled={busy || t.action === 'review-existing-draft'} onClick={() => act('article', { topic: t.id, update: t.action === 'update-existing' })}>Prepare unpublished {t.action === 'update-existing' ? 'update' : 'article'}</button></article>)}</div></>}</section></div>}
 {view === 'content' && <><section className="ops-panel"><p className="ops-kicker">APPROVED PUBLIC PROJECTS</p><h2>Evidence into a useful draft.</h2><form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('case-study', { project: field(f, 'project'), format: field(f, 'format'), evidenceApproved: f.get('evidenceApproved') === 'on' }); }}><Label name="Public project"><select name="project">{projects.map(p => <option value={p.slug} key={p.slug}>{p.name} · {p.kind === 'demo' ? 'sample demo' : 'public source study'}</option>)}</select></Label><details><summary>Inspect portfolio evidence before approving</summary>{projects.map(p => <article key={p.slug}><h3>{p.name}</h3><p>{p.scope}</p><p>{p.limitations}</p>{p.sources.map(s => <p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}<a href={'/work/' + p.slug}>Open full evidence register</a></article>)}</details><Label name="Content format"><select name="format"><option value="case-study">Case study</option><option value="walkthrough">Technical walkthrough</option><option value="social">Social draft</option></select></Label><label className="ops-check"><input name="evidenceApproved" type="checkbox" required/> I reviewed the selected public evidence and its limitations.</label><button className="ops-primary" disabled={busy}>Prepare content draft</button></form></section><div className="ops-content-list">{state?.content.map(d => <DraftEditor key={d.id + ':' + d.version + ':' + d.approvedVersion} draft={d} busy={busy} edit={body => act('content-edit', { draftId: d.id, body })} approve={() => act('content-approve', { draftId: d.id, version: d.version })}/>)}</div></>}
 {view === 'reporting' && <section className="ops-panel"><p className="ops-kicker">SOURCE ATTRIBUTION</p><h2>Observed records, not forecasts.</h2><label className="ops-check"><input type="checkbox" checked={includeSamples} onChange={e => setIncludeSamples(e.target.checked)}/> Include labeled sample records</label><p>{includeSamples ? 'Sample-inclusive view. This is not live acquisition performance.' : 'Only non-sample records are included. Public support requests are shown separately by source and do not imply buyer intent.'}</p><div className="ops-report-grid">{[...new Set(state?.leads.filter(l => includeSamples || !l.sample).map(l => l.source))].map(source => { const ls = state!.leads.filter(l => l.source === source && (includeSamples || !l.sample)); return <article key={source}><h3>{source}</h3><dl>{Object.entries({ 'Inquiries / requests': ls.length, 'Qualified records': ls.filter(l => l.qualified).length, 'Calls recorded': ls.filter(l => l.events.some(e => e.type === 'call')).length, 'Proposals advanced': ls.filter(l => l.events.some(e => e.type === 'stage' && e.detail === 'proposal')).length, 'Won agreements': ls.filter(l => l.wonValue !== null).length, 'Recorded agreement value (USD)': ls.reduce((n, l) => n + (l.wonValue || 0), 0) }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></article>; })}</div><p className="ops-muted">Calls count records with at least one recorded call. Proposals count a recorded transition after approval. Won value is a manually confirmed agreement, not collected revenue. Direct sources are unattributed unless source detail is supplied. Savings, market search volume and conversion lift are unmeasured.</p></section>}
 {view === 'activity' && <div className="ops-sections"><section className="ops-panel"><h2>Research & provider runs</h2>{jobs.slice().reverse().map(j => <article className="ops-job" key={j.id}><h3>{j.kind} <span className="ops-tag">{j.status}</span></h3><p>{new Date(j.startedAt).toLocaleString('en-GB', {timeZone:'Asia/Karachi'})} · {j.attempts} attempts · {j.reservedCalls} model calls reserved</p>{j.error && <><p className="ops-error">{j.error}</p>{j.kind === 'blog-writer-draft' && <button disabled={busy} onClick={() => act('article', { resumeJobId: j.id })}>Resume saved article review</button>}{j.kind === 'public-request-discovery' && <button disabled={busy} onClick={() => act('discover')}>Retry public research manually</button>}</>}{j.status === 'running' && <><p>Refresh after completion. If a run was interrupted, inspect the saved job before starting a fresh manual run.</p><button disabled={busy} onClick={() => act('recover-job', { jobId: j.id })}>Mark inspected job interrupted (after 10 minutes)</button></>}<details><summary>Evidence, result & recovery diagnostics</summary><pre>{json(j.result || { recovery: 'No output available. Inspect account/provider access, then retry manually. Sending and publication remain blocked.' })}</pre></details></article>)}</section><section className="ops-panel"><h2>Audit history</h2><ol className="ops-timeline">{state?.audit.slice(-100).reverse().map(a => <li key={a.id}><strong>{a.action}</strong><span>{a.actor} · {new Date(a.at).toLocaleString('en-GB', {timeZone:'Asia/Karachi'})}</span><p>{a.detail || a.target}</p></li>)}</ol></section></div>}
 {view === 'settings' && <div className="ops-sections"><section className="ops-panel"><h2>{state?.config.offer}</h2><p>{state?.config.offerAssumption}</p><h3>Private storage</h3><p>{storage || 'Encrypted private storage configured by the server.'}</p><p>Initial operating limit: 500 lead records, 700 KB encrypted state. GitHub compare-and-swap prevents lost concurrent changes. This is a low-volume store; migrate to a private database before growing beyond these limits.</p><h3>AI spending</h3><p>AI is disabled until current model rates and a daily dollar ceiling are configured. Maximum {state?.config.providerDailyLimit} reserved attempts per UTC day. Reservations remain charged to the local limit after failure. Billing is controlled by the provider; reservations are conservative estimates.</p></section><section className="ops-panel"><h2>Activation stays deliberate.</h2><p>All recurring jobs are disabled. Proposed schedules: public request review weekly; SEO plan monthly after a Search Console export; follow-up checks each business day. These jobs prepare drafts only. No external sending or publication adapter is installed.</p><p>Research uses GitHub’s existing API quota and Vercel hosting. Model usage is variable and requires current account pricing. Existing hosting/API allowances have not been represented as a guaranteed zero cost.</p><p>Approve an individual current draft, then download it for manual use. An edit, evidence withdrawal or opt-out revokes approval. Pricing and commitments are approved within each proposal.</p><a href="/privacy">Privacy and deletion contact</a></section></div>}
 <footer className="ops-footer">Private workspace · Times: Asia/Karachi · No unattended messages · Sample data excluded from reporting by default</footer></div></div>;
}
function LeadDetail({ lead: l, busy, act, now }: {
    lead: Lead;
    busy: boolean;
    act: (a: string, d: Record<string, unknown>) => Promise<boolean>;
    now: number;
}) {
    const [tab, setTab] = useState('requirements');
    const withLead = (a: string, d: Record<string, unknown> = {}) => act(a, { leadId: l.id, ...d });
    return <section className="ops-detail"><header><div><p className="ops-kicker">{l.sample ? 'SAMPLE RECORD' : 'PRIVATE RECORD'} / {l.source}</p><h2>{l.name}</h2><p>{l.email || 'No contact address supplied'} · {l.company || 'Company unknown'}</p></div><span className="ops-tag">{l.stage}</span></header><div className="ops-next"><strong>Next action</strong><p>{l.nextAction}</p>{l.dueAt && <span>Due {new Date(l.dueAt).toLocaleString('en-GB', {timeZone:'Asia/Karachi'})}</span>}</div><nav className="ops-tabs" aria-label="Lead sections">{['requirements', 'evidence', 'discovery', 'drafts', 'history'].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
 {tab === 'requirements' && <><p className="ops-brief">{l.message}</p><p className="ops-muted">Source detail: {l.sourceDetail || 'Unattributed direct inquiry'}<br />Missing: {l.missing.join(', ') || 'No discovery field gaps. Business fit needs review.'}</p><form className="ops-grid-form" onSubmit={e => { e.preventDefault(); withLead('qualify', Object.fromEntries(new FormData(e.currentTarget))); }}>{(['tools', 'volume', 'budget', 'timeline'] as const).map(k => <Label key={k} name={({ tools: 'Tools and access', volume: 'Frequency / volume', budget: 'Budget', timeline: 'Target timing' })[k]}><input name={k} defaultValue={l[k]} maxLength={600}/></Label>)}<button disabled={busy}>Save qualification</button></form><div className="ops-actions"><button disabled={busy || l.missing.length > 0 || l.qualified || l.optedOut || l.declined} onClick={() => withLead('approve-qualification', { fitConfirmed: true })}>{l.qualified ? 'Fit and qualification approved' : 'Confirm service fit and qualification'}</button><button disabled={busy || l.optedOut || l.declined || !l.email} onClick={() => withLead('reply')}>Draft inquiry reply</button><button disabled={busy || l.stage !== 'inquiry'} onClick={() => withLead('stage', { stage: 'discovery' })}>Move to discovery</button><button disabled={busy} onClick={() => withLead('decline')}>Record decline</button><button disabled={busy} onClick={() => withLead('opt-out')}>Record opt-out</button></div>{(l.optedOut || l.declined) && <p className="ops-error">Contact is closed. Draft approvals and reminders have been revoked.</p>}<form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); withLead('schedule', { dueAt: new Date(field(f, 'dueAt')+'+05:00').toISOString(), nextAction: field(f, 'nextAction') }); }}><h3>Plan the next action</h3><Label name="Follow-up time (Asia/Karachi)"><input name="dueAt" type="datetime-local" required/></Label><Label name="Next action"><input name="nextAction" required defaultValue="Review progress before drafting a follow-up"/></Label><button disabled={busy || l.optedOut || l.declined}>Schedule reminder only</button><button type="button" disabled={busy || !l.dueAt || Date.parse(l.dueAt) > now} onClick={() => withLead('follow-up')}>Draft due follow-up</button></form><form onSubmit={e => { e.preventDefault(); withLead('call', { detail: field(new FormData(e.currentTarget), 'detail') }); }}><Label name="Actual call notes"><input name="detail" required/></Label><button disabled={busy}>Record completed call</button></form></>}
 {tab === 'evidence' && <><form onSubmit={e => { e.preventDefault(); withLead('evidence', Object.fromEntries(new FormData(e.currentTarget))); }}><Label name="Evidence URL"><input name="url" type="url" required placeholder="https://github.com/n8n-io/n8n/issues/…"/></Label><Label name="Source date"><input type="date" name="date" required/></Label><Label name="Evidence kind"><select name="kind"><option value="public-request">Public request</option><option value="supplied-workflow">Supplied workflow</option></select></Label><Label name="Exact evidence / supplied workflow notes"><textarea name="text" required rows={4} maxLength={12000}/></Label><button disabled={busy}>Add evidence for review</button></form>{l.evidence.map(e => <article className="ops-evidence" key={e.id}><a href={e.url} target="_blank" rel="noreferrer">Source · {e.date}</a><p className="ops-brief">{e.text}</p><p>{e.reviewed ? 'Reviewed evidence' : 'Awaiting evidence review'}{e.retrievedAt ? ' · Retrieved ' + new Date(e.retrievedAt).toLocaleString('en-GB', {timeZone:'Asia/Karachi'}) : ''}</p><button disabled={busy} onClick={() => withLead('review-evidence', { evidenceId: e.id, approved: !e.reviewed })}>{e.reviewed ? 'Withdraw evidence approval' : 'Approve this evidence'}</button></article>)}<div className="ops-actions"><button disabled={busy} onClick={() => withLead('assessment')}>Draft technical assessment</button><button disabled={busy} onClick={() => withLead('outreach')}>Prepare outreach draft</button></div><p className="ops-muted">A reviewed source establishes an observation or report. Runtime behavior, access and business value still require verification.</p></>}
 {tab === 'discovery' && <><form onSubmit={e => { e.preventDefault(); withLead('discovery', { notes: field(new FormData(e.currentTarget), 'notes') }); }}><Label name="Discovery notes"><textarea name="notes" defaultValue={l.notes} rows={8} required maxLength={12000}/></Label><button disabled={busy}>Save discovery notes</button></form><button disabled={busy || !l.notes || l.notesApproved} onClick={async () => { const bytes = new TextEncoder().encode(JSON.stringify(l.notes)); const digest = await crypto.subtle.digest('SHA-256', bytes); const notesHash = Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join(''); withLead('approve-discovery', { notesHash }); }}>{l.notesApproved ? 'Discovery notes approved' : 'Approve saved discovery notes'}</button><form onSubmit={e => { e.preventDefault(); withLead('proposal', { price: Number(field(new FormData(e.currentTarget), 'price')) }); }}><Label name="Internal proposed price (USD)"><input name="price" type="number" min="1" max="100000" step="0.01" required/></Label><button disabled={busy || !l.notesApproved}>Draft proposal</button></form><div className="ops-actions"><button disabled={busy || l.stage !== 'discovery'} onClick={() => withLead('stage', { stage: 'proposal' })}>Advance approved proposal</button><button disabled={busy || l.stage !== 'proposal'} onClick={() => withLead('stage', { stage: 'won', agreementConfirmed: true })}>Record confirmed agreement as won</button><button disabled={busy || l.stage !== 'won'} onClick={() => withLead('stage', { stage: 'handoff' })}>Prepare delivery handoff</button></div><p className="ops-muted">Mark won only after an actual external agreement. This button records your confirmation; it does not send a proposal or accept work.</p></>}
 {tab === 'drafts' && <>{l.drafts.length === 0 && <p className="ops-empty">Prepare a reply, assessment or proposal from its lead section.</p>}{l.drafts.slice().reverse().map(d => <DraftEditor key={d.id + ':' + d.version + ':' + d.approvedVersion} draft={d} busy={busy} edit={(body, price) => withLead('edit-draft', { draftId: d.id, body, ...(price !== undefined ? { price } : {}) })} approve={() => withLead('approve-draft', { draftId: d.id, version: d.version })}/>)}</>}
 {tab === 'history' && <ol className="ops-timeline">{l.events.slice().reverse().map((e, i) => <li key={i}><strong>{e.type}</strong><span>{new Date(e.at).toLocaleString('en-GB', {timeZone:'Asia/Karachi'})}</span><p>{e.detail}</p></li>)}</ol>}
 </section>;
}
function DraftEditor({ draft: d, busy, edit, approve }: {
    draft: Draft;
    busy: boolean;
    edit: (body: string, price?: number) => Promise<boolean>;
    approve: () => Promise<boolean>;
}) { const [body, setBody] = useState(d.body), [price, setPrice] = useState(d.price), [checked, setChecked] = useState(false); const dirty = body !== d.body || price !== d.price, approved = d.approvedVersion === d.version; return <article className="ops-draft"><div className="ops-row-top"><h3>{d.kind}</h3><span className="ops-tag">{approved ? 'Approved' : 'Review required'} · v{d.version}</span></div>{d.price && <><p>Recorded proposed USD {d.price.toFixed(2)} · approval includes this price and stated terms.</p><Label name="Internal draft price (USD)"><input type="number" min="1" step="0.01" value={price} onChange={e => { setPrice(Number(e.target.value)); setChecked(false); }}/></Label><p className="ops-muted">The proposal text must include the matching USD price with two decimal places before approval.</p></>}<Label name={`Editable ${d.kind} draft`}><textarea rows={12} value={body} maxLength={30000} onChange={e => { setBody(e.target.value); setChecked(false); }}/></Label><div className="ops-actions"><button disabled={busy || !dirty} onClick={() => edit(body, price)}>Save draft changes</button>{!approved && <><label className="ops-check"><input type="checkbox" checked={checked} disabled={dirty} onChange={e => setChecked(e.target.checked)}/> I reviewed facts, recipient, scope and all terms.</label><button disabled={busy || dirty || !checked} className="ops-primary" onClick={approve}>Approve this version</button></>}{approved && !dirty && <a className="ops-download" href={'/api/ops/export?draft=' + d.id}>Download approved draft</a>}</div><p className="ops-muted">Approval permits manual export only. Nothing is sent, published or committed. Edits revoke approval.</p></article>; }
