import Link from 'next/link';
import { getPostBySlug, getAllPosts, getRelatedPosts } from '@/lib/posts';
import { renderMarkdown } from '@/lib/markdown';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
export function generateStaticParams() { return getAllPosts().map(({slug}) => ({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata> {
  const {slug}=await params; const post=getPostBySlug(slug); if(!post) return {robots:{index:false,follow:false}};
  const url=`https://www.buildzn.com/blog/${slug}`;
  return {title:post.title,description:post.excerpt,alternates:{canonical:url},openGraph:{title:post.title,description:post.excerpt,url,type:'article',publishedTime:post.date,modifiedTime:post.updated||post.date,authors:['Umair Bilal'],images:[{url:`${url}/opengraph-image`,width:1200,height:630,alt:post.title}]},twitter:{card:'summary_large_image',title:post.title,description:post.excerpt,images:[`${url}/opengraph-image`]}};
}
export default async function Article({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const post=getPostBySlug(slug); if(!post) notFound();
  const related=getRelatedPosts(slug,post.tags,3); const url=`https://www.buildzn.com/blog/${slug}`;
  const schema={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.excerpt,datePublished:post.date,dateModified:post.updated||post.date,url,author:{'@id':'https://www.buildzn.com/#person'},publisher:{'@id':'https://www.buildzn.com/#organization'},mainEntityOfPage:{'@type':'WebPage','@id':url},image:`${url}/opengraph-image`};
  return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><header className="shell article-header"><Link href="/blog" className="breadcrumb">← All insights</Link><div className="tags">{post.tags.slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div><h1>{post.title}</h1><p className="section-copy">{post.excerpt}</p><p className="article-meta">Umair Bilal · {new Date(post.date).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})} · {post.readTime}{post.updated && ` · Updated ${post.updated}`}</p></header><article className="shell article-body">{!post.reviewed && <aside className="archive-note">From the article archive. Model versions, pricing and experimental claims may have changed; this article has not yet passed the updated editorial review. Check current documentation before relying on technical instructions.</aside>}<div className="prose-custom" dangerouslySetInnerHTML={{__html:renderMarkdown(post.content)}}/><div className="article-author"><strong>Umair Bilal</strong><p>The developer behind BuildZn. Flutter apps, Node.js backends, SaaS products and AI integrations.</p><Link href="/about">About Umair ↗</Link></div><div className="scope-note"><div><h3>Have a similar product problem?</h3><p>Share the users, constraints and what needs to work better.</p></div><Link href="/#contact" className="button button-small">Discuss your project ↗</Link></div>{related.length>0 && <section style={{marginTop:50}}><h2 style={{fontSize:25}}>Related notes</h2><div className="blog-grid">{related.map(p=><article className="article-card" key={p.slug}><h2><Link href={`/blog/${p.slug}`}>{p.title}</Link></h2><p>{p.excerpt}</p></article>)}</div></section>}</article></main>;
}
